# Generated by Django 4.2 on 2024-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
